### ISSUE TITLE
convertToCaffe error while convert to the caffemodel

### ISSUE THREAD

**Issue by lsm1993** [Wulingtian/yolov5_onnx2caffe#11]
hi, when i run the command "**convertToCaffe(graph, prototxt_path, caffemodel_path)**" i met an error
it shows 
0830 09:56:36.269757  7241 net.cpp:86] Creating Layer Slice_39
I0830 09:56:36.269780  7241 net.cpp:408] Slice_39 <- 161
I0830 09:56:36.269811  7241 net.cpp:382] Slice_39 -> 166slice_another
I0830 09:56:36.269843  7241 net.cpp:382] Slice_39 -> 166
I0830 09:56:36.269876  7241 net.cpp:124] Setting up Slice_39
I0830 09:56:36.269896  7241 net.cpp:131] Top shape: 1 3 704 320 (675840)
I0830 09:56:36.269923  7241 net.cpp:131] Top shape: 1 3 704 704 (1486848)
I0830 09:56:36.269950  7241 net.cpp:139] Memory required for data: 138412032
I0830 09:56:36.269973  7241 layer_factory.hpp:77] Creating layer Concat_40
I0830 09:56:36.270002  7241 net.cpp:86] Creating Layer Concat_40
I0830 09:56:36.270023  7241 net.cpp:408] Concat_40 <- 136
I0830 09:56:36.270049  7241 net.cpp:408] Concat_40 <- 146
I0830 09:56:36.270073  7241 net.cpp:408] Concat_40 <- 156
I0830 09:56:36.270099  7241 net.cpp:408] Concat_40 <- 166
I0830 09:56:36.270128  7241 net.cpp:382] Concat_40 -> 167
F0830 09:56:36.270169  7241 concat_layer.cpp:42] Check failed: top_shape[j] == bottom[i]->shape(j) (320 vs. 704) All inputs must have the same shape, except at concat_axis.
*** Check failure stack trace: ***
it seems different from your yolov5s-4.0-not-focus-deconv.prototxt,(such as slice) and i have modified the upsample ('ConvTranspose2d') and focus(Conv) in yolov5s.yaml . Besides, i aslo change the input size of the images, but i don't think it influence the results, have you ever met this question? Thanks!

**Comment by lsm1993** [comment]
sorry, i make a mistake, and forget to modify the train.py

**Comment by vgg4resnet** [comment]
same question here ? how do u solver this ?
F0917 06:48:21.651490 21666 slice_layer.cpp:43] Check failed: slice_point_.size() == top.size() - 1 (2 vs. 1) 
*** Check failure stack trace: ***
Aborted (core dumped)
![image](https://user-images.githubusercontent.com/44825736/133764705-7d5a9b71-6605-4276-a72d-9611a4e73543.png)
![image](https://user-images.githubusercontent.com/44825736/133764942-d0ddad95-9e9c-481c-bfaa-ab3802cfdcbe.png)
 according the caffe documents 
the slice points should be <  top -1 outputs number?
![image](https://user-images.githubusercontent.com/44825736/133765308-1ee7c1fb-a520-4564-adae-26df0b888ef0.png)

**Comment by vgg4resnet** [comment]
![image](https://user-images.githubusercontent.com/44825736/133772003-ee49a73d-e0ad-4a6b-a138-056688a05be0.png)
    #layer = myf('Slice', node_name, [input_name], [output_name1,output_name2], slice_dim=axis, slice_point=[0,split])
    layer = myf('Slice', node_name, [input_name], [output_name1,output_name2], slice_dim=axis, slice_point=[split])    


may solver  the problem ？

**Comment by zxt-triumph** [comment]
> ![image](https://user-images.githubusercontent.com/44825736/133772003-ee49a73d-e0ad-4a6b-a138-056688a05be0.png) #layer = myf('Slice', node_name, [input_name], [output_name1,output_name2], slice_dim=axis, slice_point=[0,split]) layer = myf('Slice', node_name, [input_name], [output_name1,output_name2], slice_dim=axis, slice_point=[split])
> 
> may solver the problem ？



> same question here ? how do u solver this ? F0917 06:48:21.651490 21666 slice_layer.cpp:43] Check failed: slice_point_.size() == top.size() - 1 (2 vs. 1) *** Check failure stack trace: *** Aborted (core dumped) ![image](https://user-images.githubusercontent.com/44825736/133764705-7d5a9b71-6605-4276-a72d-9611a4e73543.png) ![image](https://user-images.githubusercontent.com/44825736/133764942-d0ddad95-9e9c-481c-bfaa-ab3802cfdcbe.png) according the caffe documents the slice points should be < top -1 outputs number? ![image](https://user-images.githubusercontent.com/44825736/133765308-1ee7c1fb-a520-4564-adae-26df0b888ef0.png)

Have you solved it?

**Comment by lsm1993** [comment]
This is an automatic reply, confirming that your email was received.I will reply as soon as possible.Thank youSiming Lian

**Comment by KOBE082410** [comment]
<img width="670" alt="cd2f977d5c273b1a69d69864c7d3b50" src="https://github.com/user-attachments/assets/083d5c71-52da-4525-9268-8a82b8686f22">

Hello, could you tell me which file this line of code is in?

**Comment by lsm1993** [comment]
This is an automatic reply, confirming that your email was received.I will reply as soon as possible.Thank youSiming Lian
