### ISSUE TITLE
> 我也遇到了，解决办法在.pt文件转换onnx的时候加上--train；

### ISSUE THREAD

**Issue by huangzongmou** [Wulingtian/yolov5_onnx2caffe#14]
> 我也遇到了，解决办法在.pt文件转换onnx的时候加上--train；
> eg:"python ./models/export.py --weights ./models/*.pt --img-size * --batch 1 --opset-version 10 --train";可以这样尝试能不能解决KeyError: '395'的错误

感谢，通过加上--train，去掉了网络结构最后的后处理部分，转换成功了。

_Originally posted by @wllkk in https://github.com/Wulingtian/yolov5_onnx2caffe/issues/9#issuecomment-862171037_

**Comment by heylary** [comment]
请问我加--train提示没有这个参数，是我的版本问题吗？

**Comment by huangzongmou** [comment]
您好！您的邮件已收到，尽快给你回复。谢谢                                                      黄总谋！
