### ISSUE TITLE
caffe转nnie问题

### ISSUE THREAD

**Issue by CasonTsai** [Wulingtian/yolov5_onnx2caffe#8]
请问大佬，按照您的博客https://blog.csdn.net/Yong_Qi2015/article/details/114362223替换掉focus和upsample后重新训练，然后转成caffe，执行推理的结果是没错的，但是放到ruyistudio里面转换时候显示[Transpose_217]. error:Permute can only support (0,1,2,3) -> (0,2,3,1) order!的错误，请问caffe转nnie的步骤是如何的

**Comment by sunzhongwu** [comment]
你可以去看nihui的知乎：https://zhuanlan.zhihu.com/p/275989233

**Comment by sunzhongwu** [comment]
你可以去看nihui的知乎：https://zhuanlan.zhihu.com/p/275989233

**Comment by CasonTsai** [comment]
@sunzhongwu 谢谢

**Comment by tensorflowt** [comment]
> 请问大佬，按照您的博客[https://blog.csdn.net/Yong_Qi2015/article/details/114362223替换掉focus和upsample后重新训练，然后转成caffe，执行推理的结果是没错的，但是放到ruyistudio里面转换时候显示[Transpose_217]](https://blog.csdn.net/Yong_Qi2015/article/details/114362223%E6%9B%BF%E6%8D%A2%E6%8E%89focus%E5%92%8Cupsample%E5%90%8E%E9%87%8D%E6%96%B0%E8%AE%AD%E7%BB%83%EF%BC%8C%E7%84%B6%E5%90%8E%E8%BD%AC%E6%88%90caffe%EF%BC%8C%E6%89%A7%E8%A1%8C%E6%8E%A8%E7%90%86%E7%9A%84%E7%BB%93%E6%9E%9C%E6%98%AF%E6%B2%A1%E9%94%99%E7%9A%84%EF%BC%8C%E4%BD%86%E6%98%AF%E6%94%BE%E5%88%B0ruyistudio%E9%87%8C%E9%9D%A2%E8%BD%AC%E6%8D%A2%E6%97%B6%E5%80%99%E6%98%BE%E7%A4%BA%5BTranspose_217%5D). error:Permute can only support (0,1,2,3) -> (0,2,3,1) order!的错误，请问caffe转nnie的步骤是如何的

你好！请问你后来转换nnie模型成功了吗？

**Comment by sunzhongwu** [comment]
把caffe后面两层去掉，就和yolov4一样了，你可以这样尝试再转wk












------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Wulingtian/yolov5_onnx2caffe"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月21日(星期三) 凌晨0:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Wulingtian/yolov5_onnx2caffe] caffe转nnie问题 (#8)





  
请问大佬，按照您的博客https://blog.csdn.net/Yong_Qi2015/article/details/114362223替换掉focus和upsample后重新训练，然后转成caffe，执行推理的结果是没错的，但是放到ruyistudio里面转换时候显示[Transpose_217]. error:Permute can only support (0,1,2,3) -&gt; (0,2,3,1) order!的错误，请问caffe转nnie的步骤是如何的
  
你好！请问你后来转换nnie模型成功了吗？

**Comment by larryKra** [comment]
请问一下这个问题是怎么解决的？

**Comment by jiejiangd** [comment]
您好，想请教一下如何仿真测试啊，我想在yolov3的基础上改，但是一直报错
n:1, c:255, h:52, w:52
error grid number!
没有头绪，也找不到资料
